defmodule Eatbeep.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    create table(:menus, primary_key: false) do
      add(:id, :text, null: true, default: nil, primary_key: true)
      add(:updated_at, :utc_datetime, null: true, default: fragment("now()"), primary_key: false)

      add(:tenant_id, references("tenants", type: :text, column: :id),
        default: nil,
        primary_key: false
      )

      add(:name, :text, null: false, default: nil, primary_key: false)
      add(:created_at, :utc_datetime, null: true, default: fragment("now()"), primary_key: false)
    end
  end

  def down() do
    drop(table("menus"))
  end
end