defmodule Eatbeep.Repo.Migrations.MigrateResources3 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    alter table(:menus) do
      modify(:tenant_id, :text, null: false)
    end
  end

  def down() do
    alter table(:menus) do
      modify(:tenant_id, :text, null: true)
    end
  end
end